#cloud-config
apt_update: true
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    lock_passwd: false
    plain_text_passwd: 'password'        
# login ssh and console with password
ssh_pwauth: true
disable_root: false
packages:
  - nginx
write_files:
 - content: |
    events {
      worker_connections 100;
    }
    http {
      ##
      # Basic Settings
      ##
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 65;

      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      ##
      # SSL Settings
      ##
      ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
      ssl_prefer_server_ciphers on;

      ##
      # Logging Settings
      ##
      access_log /var/log/nginx/access.log;
      error_log /var/log/nginx/error.log;

      ##
      # Servers
      ##
      upstream servers {
        server 10.1.38.42:80;
        server 10.1.38.43:80;
      }

      server {
        listen 80;
        location / {
          proxy_pass http://servers;
        }
      }
    }
   path: /etc/nginx/nginx.conf
runcmd: 
  - sudo systemctl restart nginx.service